name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    branches:
      - master
jobs:
  checks:
    name: Checking manifest and deps
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - name: Unit tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build